### ISSUE TITLE
Unable to deploy GPU workload

### ISSUE THREAD

**Issue by raphaeltm** [defang-io/defang#53]
GPU service won't deploy for some reason. 

### Docker Compose
```
version: '3.9'
services:
  gpu-dev:
    image: ubuntu:latest
    deploy:
      replicas: 1
      resources:
        reservations:
          cpus: '2.0'
          memory: 8192M
          devices:
            - capabilities: ["gpu"]
```

### Logs
```
➜  gpu-dev git:(byoc-docs) ✗ defang compose up --verbose
 - Reading access token from file /Users/raphaeltitsworth-morin/.local/state/defang/fabric-prod1.defang.dev
 - Using tenant raphaeltm for cluster fabric-prod1.defang.dev and provider auto
 * Connecting to fabric-prod1.defang.dev:443
 * Using AWS provider
 - Loading compose file docker-compose.yml for project raphaeltm
name: raphaeltm
services:
    gpu-dev:
        deploy:
            replicas: 1
            resources:
                reservations:
                    cpus: "2.0"
                    memory: "8589934592"
                    devices:
                        - capabilities:
                            - gpu
        image: ubuntu:latest
        networks:
            default: null
networks:
    default:
        name: raphaeltm_default

 * Deploying service gpu-dev
gpu-dev:
    etag: ax3zjlp56bvw
    service:
        deploy:
            replicas: 1
            resources:
                reservations:
                    cpus: 2
                    devices:
                        - capabilities:
                            - gpu
                    memory: 8192
        image: ubuntu:latest
        internal: true
        name: gpu-dev
        platform: LINUX_ANY
    status: UPDATE_QUEUED
    tenant: raphaeltm

 * Service gpu-dev is in state UPDATE_QUEUED 
 * Tailing logs for deployment ID ax3zjlp56bvw ; press Ctrl+C to detach:
20:04:02.593000 cd pulumi > @defang-io/defang-mvp@0.4.50 start
20:04:02.593000 cd pulumi > node lib/index.js up Cl8KNQoHZ3B1LWRldhINdWJ1bnR1OmxhdGVzdBgCIAEqFwgBEhMKEQ0AAABGFQAAAEAaBQoDZ3B1GglyYXBoYWVsdG0iDGF4M3pqbHA1NmJ2dyoNVVBEQVRFX1FVRVVFRA== fabric-prod1.defang.dev:443 eyJhbGciOiJFZERTQSIsImtpZCI6IjdsbnplamEzempkciIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2ZhYnJpYy5kZWZhbmcuaW8vIiwic3ViIjoicmFwaGFlbHRtIiwiZXhwIjoxNzA2NDEyNDc5fQ.dK7pwwUVey0ip-wtiqE31Cu9o_LI-_qE5jhCMxrHDUSUX9dHqRLIVvbuREkllLHW9To6vGJ17m_u5HQG8pAQDQ
20:04:02.787000 cd pulumi Initializing stack...
20:04:03.687000 cd pulumi Run update...
20:04:04.510000 cd pulumi Updating (raphaeltm):
20:04:06.152000 cd pulumi @ updating...
20:04:06.153000 cd pulumi .
20:04:07.162000 cd pulumi .
20:04:17.357000 cd pulumi     defang-mvp:shared/ecs:Kaniko kaniko 
20:04:17.357000 cd pulumi     defang-mvp:shared/ecs/cluster:EcsCluster cluster 
20:04:17.794000 cd pulumi  +  defang-mvp:shared/ecs/cluster:EcsCluster gpu-cluster creating (0s)
20:04:17.817000 cd pulumi     aws:s3:Bucket alb-logs 
20:04:18.128000 cd pulumi @ updating....
20:04:18.944000 cd pulumi     aws:iam:Role ecs-agent-profile 
20:04:18.953000 cd pulumi     aws:ecr:PullThroughCacheRule ecrPublicCache 
20:04:19.127000 cd pulumi @ updating....
20:04:19.794000 cd pulumi     aws:iam:Role ecs-task-execution-role 
20:04:19.810000 cd pulumi     aws:s3:Bucket defang-build 
20:04:19.833000 cd pulumi     aws:servicediscovery:HttpNamespace raphaeltm.defang.internal 
20:04:19.833000 cd pulumi     aws:iam:Role ecs-task-role 
20:04:19.833000 cd pulumi     aws:cloudwatch:LogGroup kaniko 
20:04:19.833000 cd pulumi     aws:iam:Role kaniko-task-execution-role 
20:04:19.833000 cd pulumi     aws:s3:BucketPolicy alb-logs-policy 
20:04:19.833000 cd pulumi     aws:s3:BucketPublicAccessBlock alb-logs-block 
20:04:19.833000 cd pulumi     aws:iam:InstanceProfile ecs-agent-profile 
20:04:19.897000 cd pulumi     aws:ecr:RegistryPolicy ecrRegistryPolicy 
20:04:19.897000 cd pulumi     aws:s3:BucketPublicAccessBlock defang-build-block 
20:04:19.897000 cd pulumi  +  aws:ecs:Cluster gpu-cluster creating (0s)
20:04:19.897000 cd pulumi     aws:ecs:Cluster cluster 
20:04:19.897000 cd pulumi     aws:iam:Role kaniko-task-role 
20:04:19.958000 cd pulumi     awsx:ecr:Repository raphaeltm/kaniko-build 
20:04:20.127000 cd pulumi @ updating....
20:04:20.250000 cd pulumi     aws:ecs:ClusterCapacityProviders cluster-capacity-providers 
20:04:20.877000 cd pulumi     aws:ecr:Repository raphaeltm/kaniko-build 
20:04:20.886000 cd pulumi     aws:ecr:LifecyclePolicy raphaeltm/kaniko-build 
20:04:21.128000 cd pulumi @ updating....
20:04:21.265000 cd pulumi     awsx:ecr:Repository raphaeltm/kaniko-build/cache 
20:04:21.265000 cd pulumi     aws:ecr:Repository raphaeltm/kaniko-build/cache 
20:04:21.265000 cd pulumi     aws:ecr:LifecyclePolicy raphaeltm/kaniko-build/cache 
20:04:21.480000 cd pulumi No pull-through cache or mirror found for docker.io/defangio/route53-sidecar:d7e8e11
20:04:21.480000 cd pulumi No pull-through cache or mirror found for gcr.io/kaniko-project/executor:v1.18.0
20:04:21.485000 cd pulumi     awsx:ec2:Vpc shared-vpc 
20:04:21.495000 cd pulumi     aws:ecs:TaskDefinition kanikoTaskDefArm64 
20:04:21.503000 cd pulumi     aws:ecs:TaskDefinition kanikoTaskDefAmd64 
20:04:22.122000 cd pulumi     aws:ec2:Vpc shared-vpc 
20:04:22.127000 cd pulumi @ updating....
20:04:22.150000 cd pulumi     aws:ec2:Subnet shared-vpc-private-3 
20:04:22.155000 cd pulumi     aws:ec2:InternetGateway shared-vpc 
20:04:22.163000 cd pulumi     aws:ec2:VpcEndpoint com.amazonaws.us-east-1.s3 
20:04:22.171000 cd pulumi     aws:ec2:Subnet shared-vpc-public-1 
20:04:22.179000 cd pulumi     aws:ec2:Subnet shared-vpc-private-1 
20:04:22.185000 cd pulumi     aws:ec2:Subnet shared-vpc-public-2 
20:04:22.192000 cd pulumi     aws:ec2:Subnet shared-vpc-private-2 
20:04:22.199000 cd pulumi     aws:ec2:Subnet shared-vpc-public-3 
20:04:22.203000 cd pulumi     aws:ec2:RouteTable shared-vpc-private-3 
20:04:22.252000 cd pulumi     aws:ec2:RouteTable shared-vpc-public-1 
20:04:22.260000 cd pulumi     aws:ec2:Eip shared-vpc-1 
20:04:22.263000 cd pulumi     aws:ec2:RouteTable shared-vpc-private-1 
20:04:22.266000 cd pulumi     aws:ec2:RouteTable shared-vpc-public-2 
20:04:22.269000 cd pulumi     aws:ec2:RouteTable shared-vpc-private-2 
20:04:22.288000 cd pulumi     aws:ec2:RouteTable shared-vpc-public-3 
20:04:22.295000 cd pulumi     aws:ec2:RouteTableAssociation shared-vpc-private-3 
20:04:22.297000 cd pulumi     aws:ec2:RouteTableAssociation shared-vpc-public-1 
20:04:22.302000 cd pulumi     aws:ec2:Route shared-vpc-public-1 
20:04:22.305000 cd pulumi     aws:ec2:NatGateway shared-vpc-1 
20:04:22.353000 cd pulumi     aws:ec2:RouteTableAssociation shared-vpc-private-1 
20:04:22.361000 cd pulumi     aws:ec2:RouteTableAssociation shared-vpc-public-2 
20:04:22.366000 cd pulumi     aws:ec2:Route shared-vpc-public-2 
20:04:22.367000 cd pulumi     aws:ec2:RouteTableAssociation shared-vpc-private-2 
20:04:22.376000 cd pulumi     aws:ec2:RouteTableAssociation shared-vpc-public-3 
20:04:22.381000 cd pulumi     aws:ec2:Route shared-vpc-public-3 
20:04:22.389000 cd pulumi     aws:ec2:Route shared-vpc-private-3 
20:04:22.393000 cd pulumi     aws:ec2:Route shared-vpc-private-1 
20:04:22.398000 cd pulumi     aws:ec2:Route shared-vpc-private-2 
20:04:23.084000 cd pulumi     aws:route53:Zone raphaeltm.defang.internal 
20:04:23.100000 cd pulumi     aws:ec2:SecurityGroup sg443 
20:04:23.106000 cd pulumi     aws:route53:Record soa-raphaeltm.defang.internal 
20:04:23.128000 cd pulumi @ updating....
20:04:23.184000 cd pulumi     aws:lb:LoadBalancer alb 
20:04:23.208000 cd pulumi     aws:cloudfront:Distribution https 
20:04:23.216000 cd pulumi     aws:lb:Listener http 
20:04:24.128000 cd pulumi @ updating....
20:04:25.128000 cd pulumi .
20:04:26.127000 cd pulumi .
20:04:27.128000 cd pulumi .
20:04:38.128000 cd pulumi @ updating....
20:04:39.128000 cd pulumi .
20:04:40.127000 cd pulumi .
20:04:41.127000 cd pulumi .
20:04:42.127000 cd pulumi .
20:04:47.639000 cd pulumi  +  aws:ecs:ClusterCapacityProviders gpu-cluster-capacity-providers created (10s)
20:04:47.894000 cd pulumi     pulumi:pulumi:Stack defang-raphaeltm running error: object null is not iterable (cannot read property Symbol(Symbol.iterator))
20:04:47.913000 cd pulumi     pulumi:pulumi:Stack defang-raphaeltm **failed** 2 errors; 1 warning
20:04:47.913000 cd pulumi Diagnostics:
20:04:47.913000 cd pulumi   pulumi:pulumi:Stack (defang-raphaeltm):
20:04:47.913000 cd pulumi     warning: Updating service gpu-dev
20:04:47.913000 cd pulumi     error: Unhandled exception: TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))
20:04:47.913000 cd pulumi         at parseImage (/app/shared/utils.ts:288:62)
20:04:47.913000 cd pulumi         at newDefangService (/app/cd/defang_service.ts:269:61)
20:04:47.913000 cd pulumi         at /app/cd/tenant_stack.ts:26:41
20:04:47.913000 cd pulumi         at Array.map (<anonymous>)
20:04:47.913000 cd pulumi         at new TenantStack (/app/cd/tenant_stack.ts:26:8)
20:04:47.913000 cd pulumi         at Object.program [as init] (/app/index.ts:41:5)
20:04:47.913000 cd pulumi         at processTicksAndRejections (node:internal/process/task_queues:95:5)
20:04:47.913000 cd pulumi     error: object null is not iterable (cannot read property Symbol(Symbol.iterator))
20:04:47.913000 cd pulumi Outputs:
20:04:47.913000 cd pulumi   - albArn      : "arn:aws:elasticloadbalancing:us-east-1:933841849165:loadbalancer/app/defang-raphaeltm-alb/c045911c3496bb3d"
20:04:47.913000 cd pulumi   - fqdn        : "d12mhfjfv5crmo.cloudfront.net"
20:04:47.913000 cd pulumi   - publicNatIps: [
20:04:47.913000 cd pulumi   -     [0]: "54.242.56.178"
20:04:47.913000 cd pulumi     ]
20:04:47.913000 cd pulumi   - vpcId       : "vpc-0eaf53b968fb60017"
20:04:47.913000 cd pulumi 
20:04:47.913000 cd pulumi Resources:
20:04:47.913000 cd pulumi     + 6 created
20:04:47.913000 cd pulumi     66 unchanged
20:04:47.913000 cd pulumi Duration: 33s
20:04:48.268000 cd pulumi code: -2
20:04:48.268000 cd pulumi  stdout:
20:04:48.268000 cd pulumi  stderr: Command failed with exit code 255: pulumi up --yes --skip-preview --color always --client=127.0.0.1:38829 --exec-kind auto.inline --stack raphaeltm --non-interactive
```

**Comment by lionello** [comment]
Unrelated to GPU. Was a bug in our image URL parsing: `ubuntu:latest` has no explicit repo. This was fixed in latest `secrets` branch.
